# -*- coding: utf-8 -*-
"""資料前處理.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tJsum66tmBiqpkssTAT4amQ0I8hreQNk
"""

import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

#create DataFrame
df = pd.DataFrame({'team': ['A', 'A', 'B', 'B', 'B', 'B', 'C', 'C'],
           'points': [25, 12, 15, 14, 19, 23, 25, 29]})

#view DataFrame
print(df)

df['team']

"""# Label Encoder"""

#create instance of label encoder
lab = LabelEncoder()

#perform label encoding on 'team' column
df['team'] = lab.fit_transform(df['team'])

#view updated DataFrame
print(df)